apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: http-echoes.test.com
  namespace: default
spec:
  group: test.com
  names:
    kind: HttpEcho
    plural: http-echoes
    singular: http-echo
    shortNames:
      - http-echo
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  format: int32
                text:
                  type: string
              required: ["replicas", "text"]
